name: Android CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Set up Android NDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r27c
    
    - name: Export Android Toolchain
      run: |
        NDK_BIN="${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin"
        echo "CC=$NDK_BIN/aarch64-linux-android24-clang" >> $GITHUB_ENV
        echo "CXX=$NDK_BIN/aarch64-linux-android24-clang++" >> $GITHUB_ENV
        echo "AR=$NDK_BIN/llvm-ar" >> $GITHUB_ENV
        echo "RANLIB=$NDK_BIN/llvm-ranlib" >> $GITHUB_ENV
        echo "STRIP=$NDK_BIN/llvm-strip" >> $GITHUB_ENV
    
    - name: CHMod GradleW
      run: chmod +x ./src/Platforms/Android/UI/gradlew

    - name: Install Conan
      uses: conan-io/setup-conan@v1
      with:
          cache_packages: true

    - name: Cache Cmake
      uses: actions/cache@v5
      with: 
        path: build
        key: cmake-${{ runner.os }}-android-${{ hashFiles('**/CMakeLists.txt', '**/android.cmake', '**/versioning.cmake') }}
        restore-keys: cmake-${{ runner.os }}-android-v2-
      
    - name: Install Dependencies
      run: |
          mkdir -p build
          conan install . --output-folder=build --build=missing -pr:h=./profiles/conan-android -s build_type=${{env.BUILD_TYPE}}
      
    - name: Configure CMake
      run: |
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=build/${{env.BUILD_TYPE}}/generators/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DANDROID=True
          ls -laR /home/runner/.conan2/p/

    - name: Build
      run: |
          find build -maxdepth 6 | sort
          cmake --build build --config ${{env.BUILD_TYPE}}

    - name: Upload Artifact
      uses: actions/upload-artifact@v7
      with:
        name: ClientWarden-Release.zip
        path: build/Release
        archive: true
