name: Multi Platform CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Conan
      uses: conan-io/setup-conan@v1
      with:
          cache_packages: true

    - name: Install Dependencies
      run: |
          mkdir build
          conan install . --output-folder=build --build=missing -s compiler.cppstd=20 -o "boost/*:without_cobalt=True" -s build_type=${{env.BUILD_TYPE}}
          
    - name: Configure CMake
      run: |
          ls -R
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=build/${{env.BUILD_TYPE}}/generators/conan_toolchain.cmake -G Xcode -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: |
          cmake --build build --config ${{env.BUILD_TYPE}}
          ls build/Release
